var LANGPACK = {
  "You have no remaining licenses.": "No te quedan licencias.",
  "Today %(time)s": "Hoy %(time)s",
  "User's admin status granted.": "Se le otorgó estado de administrador al usuario.",
  "Copy this link:": "Copia este vínculo:",
  "month": "mes",
  "Your download just started!": "Comenzó la descarga.",
  "code": "código",
  "Yahoo! Mail": "Yahoo! Mail",
  "Don't allow other members to edit the folder's files": "No permitir que otros miembros editen los archivos de la carpeta",
  "Add your stuff!": "Agrega tus archivos.",
  "Restored '%(folder_name)s'": "Se restauró '%(folder_name)s'",
  "Unable to upload file": "No se puede cargar el archivo.",
  "deleted executable": "ejecutable eliminado",
  "Invalid phone number": "El número de teléfono no es válido",
  "Change email address": "Cambia la dirección de correo electrónico",
  "There is a red 'X' on my Dropbox": "Hay una 'X' roja en mi Dropbox",
  "You already have a folder in your Dropbox called \"Presentation with Panda\" that you want to share with Panda. Click on the folder name.": "Ya tienes una carpeta en tu Dropbox denominada “Presentación con Panda”, la cual deseas compartir con Panda. Haz clic en el nombre de la carpeta.",
  "Deleted '%(collection_name)s'": "Se eliminó “%(collection_name)s”.",
  "Deleting...": "Eliminando...",
  "Message successfully sent to %(user_name)s.": "El mensaje se envió correctamente a %(user_name)s.",
  "Moving...": "Moviendo...",
  "Panda with a Dropbox": "Panda con un Dropbox",
  "Nov": "Nov",
  "Day": {
    "1": "Días",
    "0": "Día"
  },
  "User's password reset.": "Se restableció la contraseña del usuario.",
  "You're not allowed to put an application folder inside a special folder.": "No puedes colocar una carpeta de aplicación dentro de una carpeta especial.",
  "Uploaded %(num_completed)d of %(num_files)d file": {
    "1": "Se cargaron %(num_completed)d de %(num_files)d archivos.",
    "0": "Se cargó %(num_completed)d de %(num_files)d archivo."
  },
  "View file": "Ver archivo",
  "- %(size)s": "- %(size)s",
  "%d minute": {
    "1": "%d minutos",
    "0": "%d minuto"
  },
  "Please enter phone number": "Especifica el número de teléfono.",
  "Drag and drop doesn't support folder uploads.": "La característica de arrastrar y soltar no admite cargas de carpetas.",
  "Create new folder...": "Crear nueva carpeta...",
  "Unshared '%(name)s'": "Dejar de compartir '%(name)s'",
  "Please enter your email": "Especifica tu dirección de correo electrónico.",
  "GB": "GB",
  "Your upload failed because you are over quota.": "Tu carga generó un error porque superaste el espacio.",
  "Desktop": "Escritorio",
  "Message successfully sent to team.": "Se envió el mensaje al equipo correctamente.",
  "<h3>This folder is empty</h3> Add files using the <a href=\"/install\">desktop application</a> or the upload button above.": "<h3>Esta carpeta está vacía</h3> Agrega archivos con la <a href=\"/install\">aplicación de escritorio</a> o el botón para cargar que aparece arriba.",
  "Invalid password": "La contraseña no es válida",
  "Application info": "Información de la aplicación",
  "Remove link to '%(name)s'": "Quitar vínculo a '%(name)s'",
  "Restore a regular folder": "Restaurar una carpeta común",
  "You're not allowed to move your Public folder.": "No puedes mover tu carpeta Pública.",
  "deleted video": "video eliminado",
  "I want two Dropbox accounts on my computer": "Deseo dos cuentas de Dropbox en mi computadora",
  "Hide deleted files": "Ocultar eliminados",
  "Unlinked Twitter account.": "Se desvinculó la cuenta de Twitter.",
  "Reinstall the app": "Vuelve a instalar la aplicación",
  "Tell us your story": "Cuéntanos tu historia",
  "Panda quickly accepted the email invitation to join your shared folder. Now she can view and edit the files you shared.<br/><br/>Panda is finishing an awesome slide for her presentation and will save it in the shared folder.": "Panda aceptó inmediatamente la invitación por correo electrónico para unirse a tu carpeta compartida. Ahora, puede ver y editar los archivos que compartiste.<br/><br/>Panda están terminando una increíble diapositiva para su presentación y la guardará en la carpeta compartida.",
  "%(item_count)s item": {
    "1": "%(item_count)s elementos",
    "0": "%(item_count)s elemento"
  },
  "Successfully removed Yahoo! Mail contacts": "Tus contactos de Yahoo! Mail se eliminaron correctamente.",
  "The folder '%s' has been deleted.": "Se eliminó la carpeta '%s'.",
  "/mo": "/mes",
  "Permanently delete file?": "¿Eliminar el archivo permanentemente?",
  "Dropbox ": "Dropbox ",
  "video": "video",
  "Upload error": "Error al cargar",
  "%d file left": {
    "1": "%d archivos restantes",
    "0": "%d archivo restante"
  },
  "Share this folder": "Compartir esta carpeta",
  "Copy folder to...": "Copiar carpeta en...",
  "Renamed '%(collection_name)s'": "Se cambió el nombre de “%(collection_name)s”.",
  "Sync files outside of my computer's Dropbox folder": "Sincronizar archivos fuera de la carpeta de Dropbox de mi computadora",
  "font": "fuente",
  "I don't recognize a charge from Dropbox": "No reconozco un cobro de Dropbox",
  "Email preview": "Vista previa de correo electrónico",
  "Show in folder": "Mostrar en carpeta",
  "Copied %(count)d item to '<a id=\"reload-link\">%(location)s</a>'.": {
    "1": "Se copiaron %(count)d artículos a<a id=\"reload-link\">“%(location)s”.</a>",
    "0": "El artículo %(count)d se copió a “<a id=\"reload-link\">%(location)s</a>”."
  },
  "Too large": "Demasiado grande",
  "Are you sure you want to move %(item_count)s item to '%(destination)s'?": {
    "1": "¿Estás seguro de que deseas mover %(item_count)s elementos a “%(destination)s”?",
    "0": "¿Estás seguro de que deseas mover %(item_count)s elemento a “%(destination)s”?"
  },
  "Please use a Visa, MasterCard or American Express card.": "Usa una tarjeta Visa, MasterCard o American Express.",
  "My files don't appear on the website or another computer": "Mis archivos no aparecen en el sitio web ni en otro equipo",
  "The folder '%s' has been moved. <a href=\"/home%s\">View</a>": "Se movió la carpeta “%s”. <a href=\"/home%s\">Ver</a>",
  "Open highlighted file": "Abrir archivo resaltado",
  "Today": "Hoy",
  "Share %(file_count)s item": {
    "1": "Compartir %(file_count)s elementos",
    "0": "Compartir %(file_count)s elemento"
  },
  "Delete %(item_count)s item?": {
    "1": "¿Deseas eliminar %(item_count)s elementos?",
    "0": "¿Deseas eliminar %(item_count)s elemento?"
  },
  "Failed to load files": "Error al cargar archivos.",
  "Share a file as an email attachment": "Compartir un archivo como adjunto de correo electrónico",
  "Congrats! You just shared a folder!": "Felicitaciones. Compartiste una carpeta.",
  "Make %(person_name)s the owner of this folder?": "¿Hacer que %(person_name)s sea el propietario de esta carpeta?",
  "Two-step verification has not been changed": "No se modificó la verificación de dos pasos.",
  "I'm unable to share": "No puedo compartir",
  "Kick %(person_name)s out of %(folder_name)s?": "¿Deseas expulsar a %(person_name)s de %(folder_name)s?",
  "Congrats! You've enabled two-step verification!": "¡Felicitaciones! Habilitaste la verificación de dos pasos.",
  "Uploaded %(filename)s": "Se cargaron %(filename)s.",
  "Just shared a photo using @Dropbox": "Foto recientemente compartida a través de @Dropbox.",
  "Missing credit for a referral": "No me dieron crédito por una referencia",
  "Select people to invite": "Seleccionar las personas que deseas invitar",
  "Share a folder to collaborate with a friend or coworker on the same files.": "Comparte una carpeta o trabaja en los mismos archivos con un amigo o compañero de trabajo.",
  "Get Dropbox for mobile": "Obtén Dropbox para dispositivos móviles",
  "Delete %(file_count)s video?": {
    "1": "¿Deseas eliminar %(file_count)s videos?",
    "0": "¿Deseas eliminar %(file_count)s video?"
  },
  "Upload to '%(folder_name)s'": "Cargar a '%(folder_name)s'",
  "There are multiple copies of these photos in your Dropbox.": "Hay varias copias de estas fotos en tu Dropbox.",
  "Please enter your company name": "Ingresa el nombre de tu empresa.",
  "1 minute ago": {
    "1": "Hace {count} minuto",
    "0": "Hace {count} minuto"
  },
  "MB": "MB",
  "You can't use your primary phone as your backup": "No puedes usar tu teléfono principal como teléfono de respaldo.",
  "Search failed": "Error de búsqueda",
  "Once you sign in to Dropbox, this file will be instantly saved to your Dropbox and downloaded to all the computers linked to your account.": "Después de iniciar sesión en Dropbox, este archivo se guardará de inmediato en tu Dropbox y se descargará en todas las computadoras vinculadas con tu cuenta.",
  "Download": "Descargar",
  "Home": "Página principal",
  "Check that Dropbox is running and linked": "Verifica que Dropbox esté ejecutándose y esté vinculado.",
  "Remove %(file_count)s item?": {
    "1": "¿Deseas quitar %(file_count)s elementos?",
    "0": "¿Deseas quitar %(file_count)s elemento?"
  },
  "Enter the names or email addresses of the people you want to invite to your shared folder.": "Especifica los nombres o las direcciones de correo electrónico de las personas que deseas invitar a tu carpeta compartida.",
  "Shared %(album_name)s on Facebook": "Se compartió el álbum %(album_name)s en Facebook.",
  "Successfully posted to Twitter": "Se publicó en Twitter correctamente",
  "Aug": "Ago",
  "Successfully posted to Facebook": "Publicado en Facebook correctamente",
  "Add your stuff and earn 250MB!": "Agrega archivos y obtén hasta 250 MB de espacio.",
  "Share your favorite LOOK3 moments": "Comparte tus momentos favoritos de LOOK3",
  "%d photo": {
    "1": "%d fotos",
    "0": "%d foto"
  },
  "Restore %d item...": {
    "1": "Restaurar %d elementos...",
    "0": "Restaurar %d elemento..."
  },
  "Copying...": "Copiando...",
  "%d month ago": {
    "1": "Hace %d meses",
    "0": "Hace %d mes"
  },
  "Permanently delete %d item?": {
    "1": "¿Deseas eliminar %d elementos permanentemente?",
    "0": "¿Deseas eliminar %d elemento permanentemente?"
  },
  "All passwords reset.": "Se restauraron todas las contraseñas.",
  "Share 1 video": "Compartir 1 video",
  "I don't know my account email": "No sé cuál es el correo electrónico de mi cuenta",
  "Delete folder?": "¿Eliminar carpeta?",
  "Upload failed.  Please try upgrading to the latest version of <a id=\"adobe_link\">Adobe Flash</a> and try again.": "Error al cargar. Actualiza tu versión de <a id=\"adobe_link\">Adobe Flash</a> y vuelve a intentarlo.",
  "executable": "ejecutable",
  "Once you register for Dropbox, this folder will be instantly saved to your Dropbox and downloaded to all the computers linked to your account.": "Después de registrarte en Dropbox, este archivo se guardará de inmediato en tu Dropbox y se descargará en todas las computadoras vinculadas con tu cuenta.",
  "Deleted %d item.": {
    "1": "Se eliminaron %d elementos.",
    "0": "Se eliminó %d elemento."
  },
  "Please enter a valid postal code.": "Ingresa un código postal válido.",
  "June": "Junio",
  "I can't install Dropbox": "No puedo instalar Dropbox",
  "I receive a permissions error": "Recibo un error de permisos",
  "I don't want my files to take up space on this computer": "Deseo que mis archivos no ocupen espacio en esta computadora",
  "Rejoined shared folder successfully.": "Volviste a unirte a la carpeta compartida correctamente.",
  "Backup phone number added": "Se agregó un número de teléfono de respaldo.",
  "Invalid type": "El tipo no es válido",
  "This request could not be completed.  Please try again.": "No se pudo completar la solicitud. Vuelve a intentarlo.",
  "Permanently remove '%(folder_name)s'": "Quitar '%(folder_name)s' permanentemente",
  "Rename": "Cambiar nombre",
  "We were unable to remove your Gmail contacts": "No se pudieron eliminar tus contactos de Gmail.",
  "deleted font": "fuente eliminada",
  "deleted shortcut": "acceso directo eliminado",
  "Please enter a valid Visa/American Express/MasterCard, expiration date and postal code.": "Ingresa una tarjeta Visa, American Express o MasterCard válida, una fecha de caducidad válida y un código postal válido.",
  "Tell us why you love Dropbox": "Cuéntanos por qué te encanta Dropbox",
  "Type \"panda\" to find Panda's email address.": "Escribe “panda” para buscar la dirección de correo electrónico de Panda.",
  "%d day ago": {
    "1": "Hace %d días",
    "0": "Hace %d día"
  },
  "You can't upload files because you're out of space.": "No puedes cargar archivos porque no tienes más espacio.",
  "%fGB": "%f GB",
  "There are multiple copies of these videos in your Dropbox.": "Hay varias copias de estos videos en tu Dropbox.",
  "I forgot or can't reset my password": "Olvidé mi contraseña o no la puedo restablecer",
  "Uploaded %d file": {
    "1": "Se cargaron %d archivos.",
    "0": "Se cargó %d archivo."
  },
  "Share '%(snippeted_name)s'": "Compartir '%(snippeted_name)s'",
  "Untitled album": "Álbum sin título",
  "document": "documento",
  "Sync files with mobile": "Sincronizar los archivos con la aplicación móvil",
  "Restored app folder": "Carpeta de las aplicaciones restaurada",
  "Panda finished the presentation slide and saved it in the shared folder, so you can access it too! Click on the file to take a look.": "Panda terminó la diapositiva de la presentación y la guardó en la carpeta compartida; por lo tanto, tú también puedes acceder a ella. Haz clic en el archivo para echarle una mirada.",
  "Remove from album": "Quitar de álbum",
  "Sorry, unable to find the parent page.": "Lamentablemente, no podemos encontrar la página primaria.",
  "Finish installing and put something into your Dropbox folder!": "Finaliza la instalación y, a continuación, agrega algo a tu carpeta de Dropbox.",
  "I can't edit my files": "No puedo editar mis archivos",
  "Apr": "Abr",
  "Restored %d item": {
    "1": "Se restauraron %d elementos.",
    "0": "Se restauró %d elemento."
  },
  "%d folder": {
    "1": "%d carpetas",
    "0": "%d carpeta"
  },
  "Please enter a valid credit card number, expiration date, security code and postal code.": "Ingresa un número de tarjeta de crédito, una fecha de caducidad, un código de seguridad y un código postal válidos.",
  "Once you sign in to Dropbox, this folder will be instantly saved to your Dropbox and downloaded to all the computers linked to your account.": "Después de iniciar sesión en Dropbox, esta carpeta se guardará de inmediato en tu Dropbox y se descargará en todas las computadoras vinculadas con tu cuenta.",
  "Share link": "Compartir vínculo",
  "Drag and drop not supported. Please try the simple uploader.": "No se admite arrastrar y soltar. Intenta con el cargador simple.",
  "Follow Dropbox on Twitter": "Sigue a Dropbox en Twitter",
  "Group removed successfully.": "El grupo se quitó correctamente.",
  "Change password": "Cambiar contraseña",
  "There was an error while uploading your file.": "Error al cargar tu archivo.",
  "Go to link": "Ir al vínculo",
  "There was a problem removing '%(filename)s'": "Error al quitar “%(filename)s”.",
  "Unshare album?": "¿Deseas dejar de compartir este álbum?",
  "%(month)s %(date)s, %(year)s": "%(date)s de %(month)s, %(year)s",
  "deleted code": "código eliminado",
  "Please copy the text below:": "Copia este texto:",
  "Removed shared folder successfully.": "Se quitó la carpeta compartida correctamente.",
  "Invite friends": "Invitar amigos",
  "Delete file?": "¿Eliminar archivo?",
  "You've completed every quest, but you can still <a href='/referrals'>invite more friends</a> to Dropbox!": "¡Has completado todas las tareas, pero todavía puedes <a href='/referrals'>invitar a más amigos</a> a Dropbox!",
  "Pricing plans": "Planes de precio",
  "Revert my Dropbox back to a date and time": "Retroceder mi Dropbox a una fecha y a una hora determinadas",
  "Deleted files cannot be added to the clipboard": "No es posible agregar archivos eliminados al portapapeles.",
  "Invite to folder": "Invitar a carpeta",
  "Create account": "Crear cuenta",
  "iPhone or iPad": "iPhone o iPad",
  "Changed cover photo for '%(collection_name)s'": "Se cambió la foto de portada de '%(collection_name)s'",
  "Loading shared folder options...": "Cargando las opciones de las carpetas compartidas...",
  "Cancel my Dropbox Pro subscription": "Cancelar mi suscripción a Dropbox Pro",
  "Preview folder": "Vista previa de la carpeta",
  "All uploads canceled": "Se cancelaron todas las cargas",
  "Rejoin": "Volver a unirme",
  "%d year ago": {
    "1": "Hace %d años",
    "0": "Hace %d año"
  },
  "Create album": "Crear álbum",
  "Nice work! You earned an extra 250MB.": "¡Muy bien! Obtuviste 250 MB de espacio adicional.",
  "Unshared folder '%(folder_name)s'": "Dejar de compartir el archivo '%(folder_name)s'",
  "Just shared a video using @Dropbox": "Video recientemente compartido a través de @Dropbox.",
  "Save to %s": "Guardar en %s",
  "Uploading %(filename)s": "Cargando %(filename)s",
  "Switch my Dropbox Pro plan size": "Cambiar el tamaño de mi plan Dropbox Pro",
  "Dropbox for Business": "Dropbox para empresas",
  "%d second": {
    "1": "%d segundos",
    "0": "%d segundo"
  },
  "That file already exists in that folder.": {
    "1": "Esos archivos ya existen en esa carpeta.",
    "0": "Ese archivo ya existe en esa carpeta."
  },
  "Permanently delete": "Eliminar permanentemente",
  "Check your shared folders": "Verifica tus carpetas compartidas.",
  "Select photo": "Seleccionar foto",
  "Play slideshow": "Reproducir presentación",
  "%d item": {
    "1": "%d elementos",
    "0": "%d elemento"
  },
  "Unlink all users": "Desvincular todos los usuarios",
  "View original": "Ver original",
  "Are you sure you want to remove admin privileges for <strong>%(person_name)s</strong>?": "¿Estás seguro de que deseas quitarle los privilegios de administrador a <strong>%(person_name)s</strong>?",
  "Just shared an image using @Dropbox": "Compartí una imagen utilizando @Dropbox",
  "Please enter a valid credit card number and postal code.": "Ingresa un número de tarjeta de crédito y un código postal válidos.",
  "Click this button to start inviting collaborators to this folder.": "Haz clic en este botón para comenzar a invitar a colaboradores a esta carpeta.",
  "Show/hide keyboard shorcuts": "Mostrar/ocultar métodos abreviados del teclado",
  "File": {
    "1": "%d archivos",
    "0": "%d archivo"
  },
  "Linux": "Linux",
  "Two-step verification is still enabled": "La verificación de dos pasos todavía está habilitada.",
  "Just shared a file using @Dropbox": "Compartí un archivo utilizando @Dropbox",
  "Someone I don't know joined my shared folder": "Alguien que no conozco se unió a mi carpeta compartida",
  "Thanks for your help request.  We'll get back to you soon.": "Gracias por tu solicitud de ayuda. No comunicaremos contigo a la brevedad.",
  "Create an account": "Crear una cuenta",
  "%d day": {
    "1": "%d días",
    "0": "%d día"
  },
  "0GB": "0 GB",
  "deleted link": "vínculo eliminado",
  "Please enter a valid expiration date and security code.": "Ingresa una fecha de caducidad y un código de seguridad válidos.",
  "Customize an invoice": "Personalizar una factura",
  "Restore file?": "¿Restaurar archivo?",
  "Jan": "Ene",
  "User's admin status removed.": "Se le quitó el estado de administrador al usuario.",
  "Guess again": "Intenta nuevamente",
  "Imported Gmail contacts": "Se importaron los contactos de Gmail.",
  "Please test this app": "Prueba la aplicación",
  "Oct": "Oct",
  "It looks like you're trying to share a folder.": "Parece que quieres compartir una carpeta.",
  "Shared %(album_name)s with %(first_name_of_recipient)s": "Se compartió el álbum %(album_name)s con %(first_name_of_recipient)s.",
  "Shared %(album_name)s with %(first_name_of_recipient)s and %(num_other_recipients)s others": "Se compartió el álbum %(album_name)s con %(first_name_of_recipient)s y %(num_other_recipients)s personas más.",
  "Moving deleted folders or files is not allowed.": "No puedes mover carpetas o archivos eliminados.",
  "%d new shared folder invitation": {
    "1": "%d nuevas invitaciones a carpetas compartidas",
    "0": "%d nueva invitación a carpeta compartida"
  },
  "You need to select a destination for the file.": "Debes seleccionar un destino para el archivo.",
  "Two-step verification disabled.": "La verificación de dos pasos está inhabilitada.",
  "Delete %(file_count)s file?": {
    "1": "¿Deseas eliminar %(file_count)s archivos?",
    "0": "¿Deseas eliminar %(file_count)s archivo?"
  },
  "Disable '%(app_name)s'?": "¿Deseas habilitar “%(app_name)s”?",
  "Select all in %(folder)s": "Seleccionar todos en %(folder)s",
  "Two-step verification is already disabled. Did you maybe disable it in another window?": "La verificación de dos pasos ya está inhabilitada. ¿Quizás la inhabilitaste en otra ventana?",
  "Deleting video": {
    "1": "Eliminando videos...",
    "0": "Eliminando video..."
  },
  "Video from %(date_taken)s": "Video del %(date_taken)s",
  "Deleted video.": {
    "1": "Se eliminaron los videos.",
    "0": "Se eliminó el video."
  },
  "Full size": "Tamaño completo",
  "image": "imagen",
  "To earn even more space, continue Get Started.": "Si deseas obtener más espacio, continúa con la guía de introducción.",
  "%(name)s has invited you to join Dropbox!": "%(name)s te ha invitado a unirte a Dropbox.",
  "$%(dollars)s": "$%(dollars)s",
  "Added photo to '%(collection_name)s'": {
    "1": "Se agregaron fotos a “%(collection_name)s”.",
    "0": "Se agregó una foto a “%(collection_name)s”."
  },
  "Mobile": "Móvil",
  "Once you register for Dropbox, this file will be instantly saved to your Dropbox and downloaded to all the computers linked to your account.": "Después de registrarte en Dropbox, este archivo se guardará de inmediato en tu Dropbox y se descargará en todas las computadoras vinculadas con tu cuenta.",
  "Unlink device?": "¿Deseas desvincular el dispositivo?",
  "iPhone": "iPhone",
  "Dropbox": "Dropbox",
  "%d week ago": {
    "1": "Hace %d semanas",
    "0": "Hace %d semana"
  },
  "Please enter a valid security code.": "Ingresa un código de seguridad válido.",
  "Sorry, your phone code has expired. Please log in again.": "El código del teléfono caducó. Vuelve a iniciar sesión.",
  "Your request completed successfully.": "Tu solicitud se realizó correctamente.",
  "Link copied to clipboard!": "¡Vínculo copiado al portapapeles!",
  "The upload limit online is 300MB. You can upload larger files with the <a id=\"install_link\">Dropbox desktop application</a>.": "El límite de carga en línea es de 300 MB. Puedes cargar archivos más extensos con la <a id=\"install_link\">aplicación de escritorio de Dropbox</a>.",
  "Please enter a Twitter post": "Ingresa una publicación de Twitter",
  "Drop your file to upload to '%(folder_name)s'": "Suelta el archivo para cargarlo en '%(folder_name)s'",
  "My computer isn't syncing": "Mi equipo no sincroniza",
  "Share '%(filename)s'": "Compartir '%(filename)s'",
  "Sure!": "¡Por supuesto!",
  "In the future": "En el futuro",
  "Restore a deleted file": "Restaurar un archivo eliminado",
  "%(date)s at %(time)s": "%(date)s a las %(time)s",
  "Too many incorrect passwords. Please try again in a few minutes.": "Demasiadas contraseñas incorrectas. Vuelve a intentarlo en unos minutos.",
  "'%(filename)s' cannot be added to the clipboard": "El archivo “%(filename)s” no se puede agregar al portapapeles.",
  "deleted app folder": "carpeta de aplicación eliminada",
  "%d min ago": {
    "1": "Hace %d min",
    "0": "Hace %d min"
  },
  "I receive an error when I start Dropbox": "Ocurre un error al iniciar Dropbox",
  "Delete album?": "¿Deseas eliminar este álbum?",
  "Advanced search": "Búsqueda avanzada",
  "Get help with other issue": "Obtener ayuda con otro problema",
  "Delete %(file_count)s photo": {
    "1": "Eliminar %(file_count)s fotos",
    "0": "Eliminar %(file_count)s foto"
  },
  "Link copied to clipboard": "Vínculo copiado al portapapeles",
  "You no longer have any hosts linked.": "Ya no tienes ningún host vinculado.",
  "You have %d remaining license.": {
    "1": "Te quedan %d licencias.",
    "0": "Te queda %d licencia."
  },
  "Looks great!": "¡Me parece genial!",
  "Please enter a valid expiration date.": "Ingresa una fecha de caducidad válida.",
  "Invite friends and family to Dropbox!": "Invita a tus familiares y amigos a Dropbox.",
  "You've asked for too many SMS messages. Please try again in a few minutes.": "Has solicitado demasiados mensajes SMS. Vuelve a intentarlo en unos minutos.",
  "Dropbox developer support": "Soporte para los desarrolladores de Dropbox",
  "Two-step verification is now disabled.": "Ahora la verificación de dos pasos está deshabilitada.",
  "year": "año",
  "Share on Facebook": "Compartir en Facebook",
  "Save": "Guardar",
  "More": "Más",
  "Your download just finished!": "Se completó la descarga.",
  "This folder will be instantly saved to your Dropbox and downloaded to all the computers linked to your account.": "Esta carpeta se guardará instantáneamente en tu Dropbox y se descargará en todas las computadoras vinculadas a tu cuenta.",
  "Leave shared folder?": "¿Dejar la carpeta compartida?",
  "Move %(item_count)s item": {
    "1": "Mover %(item_count)s elementos",
    "0": "Mover %(item_count)s elemento"
  },
  "Delete %(file_count)s item": {
    "1": "Eliminar %(file_count)s elementos",
    "0": "Eliminar %(file_count)s elemento"
  },
  "Renaming...": "Cambiando nombre...",
  "%d year": {
    "1": "%d años",
    "0": "%d año"
  },
  "Verification email sent to %(email)s": "Se envió el correo electrónico de verificación a %(email)s",
  "Removed link for '%(name)s'": "Se quitó el vínculo a '%(name)s'.",
  "Please enter a Facebook post": "Especifica una publicación en Facebook.",
  "Connected": "Conectado",
  "%d hr": {
    "1": "%d h",
    "0": "%d h"
  },
  "Send your folder invitation!": "Enviar invitación a tu carpeta",
  "Kindle Fire": "Kindle Fire",
  "Since it's been a while, please enter your password again.": "Ha pasado bastante tiempo. Vuelve a introducir tu contraseña.",
  "You can't upload folders or files of this type.": "No puedes cargar carpetas o archivos de este tipo.",
  "None": "Ninguno",
  "Your tweet must be 140 characters or less": "Tu tweet debe tener 140 caracteres o menos.",
  "Extension": "Extensión",
  "I love Dropbox because %(why_msg)s %(referral_link)s": "Me encanta Dropbox porque %(why_msg)s %(referral_link)s",
  "Let's go!": "Comencemos.",
  "Make '%(person_name)s' an admin": "Designar a “%(person_name)s” como administrador",
  "Invite team members": "Invitar miembros al equipo",
  "deleted shared folder": "carpeta compartida eliminada",
  "Copy %(item_count)s item": {
    "1": "Copiar %(item_count)s elementos",
    "0": "Copiar %(item_count)s elemento"
  },
  "How Dropbox works": "Cómo funciona Dropbox",
  "Sorry, an error occurred. Please try again later.": "Ocurrió un error. Vuelve a intentarlo más adelante.",
  "My files don't appear on this computer": "Mis archivos no aparecen en este equipo",
  "Options": "Opciones",
  "Delete": "Eliminar",
  "Successfully connected to Facebook.": "La conexión con Facebook se realizó correctamente.",
  "What do you think of Panda's slide?": "¿Qué piensas acerca de la diapositiva de Panda?",
  "September": "Septiembre",
  "Restrict privileges for a shared folder": "Restringir privilegios para una carpeta compartida",
  "Exit tutorial": "Salir del tutorial",
  "Didn't receive bonus space for HTC phone": "No recibí bonificación de espacio para mi teléfono HTC",
  "Track stolen computer": "Buscar una computadora robada",
  "Oops! No contacts here.": "¡Vaya! No hay contactos aquí.",
  "Feature request": "Solicitud de características",
  "Video preview failed.": "Error al obtener la vista previa del video",
  "BlackBerry": "BlackBerry",
  "Please rename this app": "Cambia el nombre de la aplicación",
  "Delete %(num_videos)s videos and all copies?": "¿Deseas eliminar %(num_videos)s videos y todas sus copias?",
  "There are multiple copies of these files in your Dropbox.": "Hay varias copias de estos archivos en tu Dropbox.",
  "%d sec": {
    "1": "%d s",
    "0": "%d s"
  },
  "Remove %(file_count)s video?": {
    "1": "¿Deseas quitar %(file_count)s videos?",
    "0": "¿Deseas quitar %(file_count)s video?"
  },
  "Failed to unpublish the domain.": "Error al deshacer la publicación del dominio.",
  "Invalid file type": "El tipo de archivo no es válido",
  "Please enter a valid expiration date and postal code.": "Ingresa una fecha de caducidad y un código postal válidos.",
  "Deleting '%(collection_name)s'...": "Eliminando “%(collection_name)s”...",
  "%d video": {
    "1": "%d videos",
    "0": "%d video"
  },
  "Removed %(files_desc)s from '%(collection_name)s'": "%(files_desc)s se quitó de “%(collection_name)s”.",
  "Empty file": "Archivo vacío",
  "Please enter a valid credit card number, security code and postal code.": "Ingresa un número de tarjeta de crédito, un código de seguridad y un código postal válidos.",
  "Imported Yahoo! Mail contacts": "Se importaron los contactos de Yahoo! Mail.",
  "Undo a large number of changes to files and folders": "Deshacer una gran cantidad de cambios en archivos y carpetas",
  "Created folder '%(folder_name)s'": "Se creó la carpeta '%(folder_name)s'.",
  "Please enter a message": "Ingresa un mensaje",
  "Add collaborators": "Agregar colaboradores",
  "Share '%(folder_name)s' with others": "Compartir '%(folder_name)s' con otras personas",
  "Delete all copies of this photo?": "¿Deseas eliminar todas las copias de esta foto?",
  "Search for deleted files": "Busca archivos eliminados",
  "Please select a parent folder.": "Selecciona una carpeta principal.",
  "Website": "Sitio web",
  "We couldn't create a link to this album. Please try again.": "No se pudo crear un vínculo a este álbum. Vuelve a intentarlo.",
  "Invalid code. Check the clock on your phone: it must be accurate to the minute.": "El código no es válido. Observa el reloj de tu teléfono; debe tener una exactitud al minuto.",
  "Restored '%(file_name)s'": "Se restauró '%(file_name)s'",
  "Are you sure you want to copy %(item_count)s item to %(destination)s?": {
    "1": "¿Estás seguro de que deseas copiar %(item_count)s elementos a %(destination)s?",
    "0": "¿Estás seguro de que deseas copiar %(item_count)s elemento a %(destination)s?"
  },
  "Added %d item to clipboard": {
    "1": "Se agregaron %d elementos al portapapeles.",
    "0": "Se agregó %d elemento al portapapeles."
  },
  "Share link to video": "Compartir vínculo a video",
  "You can't drag and drop upload right now.": "No puedes arrastrar y soltar en este momento.",
  "You can't upload an empty file.": "No puedes cargar un archivo vacío",
  "Always have your stuff when you need it with Dropbox. Sign up for free!": "Gracias a Dropbox, tus archivos siempre estarán contigo cuando los necesites. Regístrate para crear una cuenta gratuita.",
  "I can't sign in": "No puedo iniciar sesión",
  "Remove '%(user_name)s'": "Quitar “%(user_name)s”",
  "Invalid file name": "El nombre de archivo no es válido",
  "Cancel my subscription": "Cancelar mi suscripción",
  "%(x_files)s and %(y_folders)s": "%(x_files)s y %(y_folders)s",
  "We need your permission to import your Gmail contacts": "Para importar tus contactos de Gmail, necesitamos tu permiso.",
  "Share link to '%(folder_name)s'": "Compartir este vínculo con '%(folder_name)s'",
  "Import your %(email_provider_name)s contacts": "Importar tus  contactos de %(email_provider_name)s",
  "Check the website": "Consulta el sitio web",
  "Error, unable to restore '%(file_name)s'": "Error, no fue posible restaurar '%(file_name)s'",
  "You're not using any Dropbox API apps.": "No estás usando ninguna aplicación de la API de Dropbox.",
  "Two stick figures sharing their Dropboxes": "Dos figuras de líneas que comparten sus Dropbox.",
  "Gallery view": "Vista de galería",
  "Are you sure you want to disable '%(app_name)s'?": "¿Estás seguro de que deseas inhabilitar “%(app_name)s”?",
  "Share a folder and earn 250MB!": "Comparte un archivo y obtén 250 MB de espacio.",
  "Missing dates": "Faltan fechas.",
  "%d file": {
    "1": "%d archivos",
    "0": "%d archivo"
  },
  "Copy photos to my Dropbox": "Copiar fotos a mi Dropbox",
  "Another album": "Otro álbum",
  "deleted file": "archivo eliminado",
  "Removed '%(filename)s'": "Se quitó “%(filename)s”.",
  "KB": "KB",
  "You cannot put files inside one another.": "No puedes colocar archivos dentro de archivos.",
  "Sep": "Sep",
  "Subscribe to %(folder_name)s changes feed": "Suscríbete a la fuente de cambios de %(folder_name)s",
  "Just now": "En este momento",
  "Two-step verification is disabled. Did you maybe disable it in another window?": "La verificación de dos pasos está inhabilitada. ¿Quizás la inhabilitaste en otra ventana?",
  "Download Original": "Descargar original",
  "Share photo": "Compartir foto",
  "Cancel": "Cancelar",
  "Send email to '%(user_name)s'": "Enviar correo electrónico a “%(user_name)s”",
  "Loading...": "Cargando...",
  "Set as cover": "Establecer como portada",
  "Disable link": "Deshabilitar vínculo",
  "You already have an album named '%(current_album_name)s'": "Ya tienes un álbum llamado “%(current_album_name)s”.",
  "Open highlighted folder": "Abrir carpeta resaltada",
  "shared folder": "carpeta compartida",
  "Click here to add Panda to the list of collaborators.": "Haz clic aquí para agregar a Panda a la lista de colaboradores.",
  "Forgot password": "Olvidé la contraseña",
  "Creating...": "Creando...",
  "deleted disk image": "imagen de disco eliminada",
  "Once you register for Dropbox, the photos and videos in this album will be instantly copied to your Dropbox and downloaded to all the computers linked to your account.": "Una vez que te registres en Dropbox, las fotos y los videos de este álbum se copiarán inmediatamente a tu Dropbox y se descargarán en todas las computadoras vinculadas a tu cuenta.",
  "$%(num_dollars)s": "$%(num_dollars)s",
  "Save here": "Guardar aquí",
  "We couldn't share this album on Facebook. Please try again.": "No se pudo compartir este álbum en Facebook. Vuelve a intentarlo.",
  "Sent to %(recipient)s": "Se envió a %(recipient)s.",
  "Click here to send the invitation to Panda.": "Haz clic aquí para enviar la invitación a Panda.",
  "Show files with multiple copies": "Mostrar archivos con varias copias",
  "There are multiple copies of this video.": "Hay varias copias de este video.",
  "The photos and videos in this album will be instantly copied to your Dropbox and downloaded to all the computers linked to your account.": "Las fotos y los videos de este álbum se copiarán inmediatamente a tu Dropbox y se descargarán en todas las computadoras vinculadas a tu cuenta.",
  "Shared": "Compartido",
  "Get mobile app": "Obtener una aplicación móvil",
  "Please try again. If this continues to fail, your browser might not support drag and drop uploads.": "Intenta nuevamente. Si el error continúa, puede que tu explorador no admita arrastrar y soltar para las cargas.",
  "Show videos with multiple copies": "Mostrar videos con varias copias",
  "archive": "archivo comprimido",
  "Web session closed.": "Se cerró la sesión en el sitio web.",
  "Deselect all": "Deseleccionar todos",
  "Albums": "Álbumes",
  "Please enter a comment.": "Ingresa un comentario.",
  "Prevent members from inviting others": "Impedir que los miembros inviten a otras personas",
  "This file will be instantly saved to your Dropbox and downloaded to all the computers linked to your account.": "Este archivo se guardará instantáneamente en tu Dropbox y se descargará en todas las computadoras vinculadas a tu cuenta.",
  "Close web session": "Cerrar sesión en el sitio web",
  "Members can now share this folder.": "Ahora los miembros pueden compartir esta carpeta.",
  "Move folder to...": "Mover carpeta a...",
  "Removing from album...": "Eliminando del álbum...",
  "So-so": "Más o menos",
  "Folders within shared folders can't be shared, but you can still share the folder '%(parent_shared_folder)s'": "No se pueden compartir las carpetas dentro de las carpetas compartidas, pero puedes compartir la carpeta '%(parent_shared_folder)s'",
  "Good": "Buena",
  "Up a folder": "Una carpeta hacia arriba",
  "Rename album": "Cambiar nombre de álbum",
  "Invite %d friend": {
    "1": "Invitar a %d amigos",
    "0": "Invitar a %d amigo"
  },
  "Restore": "Restaurar",
  "Unknown date": "Fecha desconocida",
  "audio": "audio",
  "I can't view a file": "No puedo ver un archivo",
  "You've earned the maximum amount of referral space. Thanks for inviting people to Dropbox!": "Has ganado la cantidad máxima de espacio por recomendaciones. ¡Gracias por invitar amigos a Dropbox!",
  "I love Dropbox because %(why_msg)s ": "Me encanta Dropbox porque %(why_msg)s ",
  "Copying to your Dropbox...": "Copiando a tu Dropbox...",
  "Very weak": "Muy débil",
  "Starting upload...": "Iniciando carga...",
  "Unshare album": "Dejar de compartir álbum",
  "Remove %(num_photos)s from album": "Quitar %(num_photos)s fotos del álbum",
  "Please enter a valid credit card number and security code.": "Ingresa un número de tarjeta de crédito y un código de seguridad válidos.",
  "Switch my billing period": "Cambiar mi período de facturación",
  "%d min": {
    "1": "%d min",
    "0": "%d min"
  },
  "Rejoin shared folder": "Volver a unirse a la carpeta compartida",
  "Sorry, your phone code has expired. Please try again.": "El código del teléfono caducó. Inténtalo otra vez.",
  "%(num_photos)s and %(num_videos)s": "%(num_photos)s y %(num_videos)s",
  "deleted audio": "audio eliminado",
  "All builds": "Todas las compilaciones",
  "Sounds good": "¡Genial!",
  "Photo from %(date)s": "Foto del %(date)s",
  "Confirm delete": "Confirmar eliminación",
  "View in Photos": "Ver en Fotos",
  "Backup phone number updated": "Se actualizó el número de teléfono de respaldo.",
  "Cancel a recurring charge for someone else": "Cancelar un cobro periódico de otra persona",
  "View details": "Ver detalles",
  "Pause slideshow": "Pausar presentación",
  "Please enter a valid Visa/American Express/MasterCard, expiration date, security code and postal code.": "Ingresa una tarjeta Visa, American Express o MasterCard válida, una fecha de caducidad válida, un código de seguridad válido y un código postal válido.",
  "Sharing": "Compartir",
  "Leaving this page will cancel your uploads.": "Al salir de esta página se cancelarán tus cargas.",
  "Delete %(file_count)s photo?": {
    "1": "¿Deseas eliminar %(file_count)s fotos?",
    "0": "¿Deseas eliminar %(file_count)s foto?"
  },
  "Undo": "Deshacer",
  "Restored files": "Se restauraron los archivos.",
  "Join Dropbox!": "Únete a Dropbox.",
  "Sign in": "Iniciar sesión",
  "My camera upload space isn't appearing": "No aparece el espacio de carga para mi cámara",
  "folder": "carpeta",
  "Delete %(num_photos)s photos and all copies?": "¿Deseas eliminar %(num_photos)s fotos y todas sus copias?",
  "Restore folder": "Restaurar carpeta",
  "Whoa there, don't take advice from a webcomic too literally ;)": "¡Epa! No tomes tan en serio los consejos de una historieta ;)",
  "Are you sure you want to uninvite %(email_or_fbname)s?": "¿Confirmas que deseas retirar la invitación de %(email_or_fbname)s?",
  "Account": "Cuenta",
  "There is a blue circle icon on my Dropbox": "Hay un icono con un círculo azul en mi Dropbox",
  "Please pick how many licenses you need": "Selecciona la cantidad de licencias que necesitas.",
  "Quota exceeded": "Se superó el espacio",
  "Why not try sharing a folder with a friend or colleague?<br/>It brings you <a href='/gs' target='_blank'>one step closer</a> to winning a 250 MB bonus!": "¿Por qué no intentas compartir una carpeta con un amigo o colega?<br/>Estarás <a href='/gs' target='_blank'>un paso más cerca</a> de ganar 250 MB.",
  "Open With...": "Abrir con...",
  "Check if files are being used": "Comprueba si hay archivos en uso",
  "Kick %(group_name)s out of %(folder_name)s?": "¿Deseas expulsar a %(group_name)s de %(folder_name)s?",
  "-$%(num_dollars)s": "-$%(num_dollars)s",
  "Sorry, an error occured. Please try again later.": "Ocurrió un error. Vuelve a intentarlo más adelante.",
  "Share %(file_count)s video": {
    "1": "Compartir %(file_count)s videos",
    "0": "Compartir %(file_count)s video"
  },
  "Move your mouse here!": "Mueve tu ratón aquí.",
  "Facebook message": "Mensaje de Facebook",
  "You cannot copy a folder into itself.": "No puedes copiar una carpeta dentro de sí misma.",
  "Added by %(fname)s": "Agregado por %(fname)s",
  "Invalid code": "El código no es válido",
  "Device unlinked.": "Se desvinculó el dispositivo.",
  "Delete %(num_files)s files and all copies?": "¿Deseas eliminar %(num_files)s archivos y todas sus copias?",
  "Move": "Mover",
  "Migration link for '%(email)s'": "Vínculo de migración para '%(email)s'",
  "Copy %(item_count)s item to...": {
    "1": "Copiar %(item_count)s elementos a...",
    "0": "Copiar %(item_count)s elemento a..."
  },
  "Undo a large number of changes": "Deshacer una gran cantidad de cambios",
  "Disabled": "Inhabilitada",
  "I can't see my file(s)": "No puedo ver mis archivos.",
  "I don't see the Dropbox icon on my computer": "No veo el icono de Dropbox en mi computadora",
  "Your password has expired. Please create a new password <a target=\"_blank\" href=\"/password_expired\">here</a>.": "Tu contraseña caducó. Debes crear una nueva contraseña <a target=\"_blank\" href=\"/password_expired\">aquí.</a>",
  "Deleted file.": {
    "1": "Se eliminaron los archivos.",
    "0": "Se eliminó un archivo."
  },
  "Please enter a valid credit card number.": "Ingresa un número de tarjeta de crédito válido.",
  "All photos and videos in your Dropbox are now shown.": "Ahora se muestran todos los videos y fotos de tu Dropbox.",
  "Gmail": "Gmail",
  "iPad": "iPad",
  "Add to album": "Agregar a álbum",
  "Share album": "Compartir álbum",
  "Linked Twitter account.": "Se vinculó la cuenta de Twitter.",
  "We couldn't share this album on Twitter. Please try again.": "No se pudo compartir este álbum en Twitter. Vuelve a intentarlo.",
  "Kind": "Tipo",
  "Please enter a valid Visa/American Express/MasterCard and security code.": "Ingresa una tarjeta Visa, American Express o MasterCard válida y un código de seguridad válido.",
  "Share '%(parent_shared_folder)s' folder": "Compartir la carpeta “%(parent_shared_folder)s” ",
  "Learn more": "Más información",
  "Open with...": "Abrir con...",
  "%(email_or_fbname)s was reinvited successfully": "Se volvió a invitar a %(email_or_fbname)s correctamente",
  "Android": "Android",
  "You need more licenses for this invitation.": "Necesitas más licencias para esta invitación.",
  "Delete selected files": "Eliminar los archivos seleccionados",
  "Share this %(type)s": "Compartir este %(type)s",
  "Undo complete": "Se completó la acción de deshacer.",
  "That phone number does not appear to be a valid mobile number.": "El número telefónico parece no ser un número de dispositivo móvil válido.",
  "Share %(num_photos)s photos": "Compartir %(num_photos)s fotos",
  "Less than a minute ago": "Hace menos de un minuto",
  "Your friend, Panda, is working on a presentation and needs your help. Let's see how we can share files with Panda and work together using Dropbox.": "Tu amigo, Panda, está trabajando en una presentación y necesita tu ayuda. Veamos cómo podemos compartir carpetas con Panda y trabajar de forma conjunta a través de Dropbox.",
  "Select all": "Seleccionar todos",
  "Deleting photo": {
    "1": "Eliminando fotos...",
    "0": "Eliminando la foto..."
  },
  "July": "Julio",
  "Didn't receive a shared folder invitation": "No recibí una invitación para una carpeta compartida",
  "%(time_left)s left": "Quedan %(time_left)s",
  "PM": "p. m.",
  "See what your collaborators are up to": "Accede a los que tus colaboradores están haciendo.",
  "This file does not have an allowed file type.": "Este archivo no tiene un tipo de archivo permitido.",
  "Remove '%(user_email)s'": "Quitar “%(user_email)s”",
  "Add to my Dropbox": "Agregar a mi Dropbox",
  "1 Comment": {
    "1": "{count} comentarios",
    "0": "{count} comentarios"
  },
  "Undoing...": "Deshaciendo...",
  "Upload": "Cargar",
  "Please enter your phone number": "Introduce tu número de teléfono",
  "User removed successfully.": "El usuario se quitó correctamente.",
  "deleted archive": "archivo comprimido eliminado",
  "Hotmail": "Hotmail",
  "Remove %(file_count)s photo?": {
    "1": "¿Deseas quitar %(file_count)s fotos?",
    "0": "¿Deseas quitar %(file_count)s foto?"
  },
  "Installing Dropbox on %(device)s": "Instalando Dropbox en %(device)s",
  "Limit raised to %d users": "El límite se amplió a %d usuarios.",
  "Unable to preview this item.": "No es posible la vista previa de este elemento.",
  "Rename complete.": "Se cambió el nombre.",
  "Pay with PayPal": "Pagar con PayPal",
  "Deleted %(file_count)s item": {
    "1": "Se eliminaron %(file_count)s elementos.",
    "0": "Se eliminó %(file_count)s elemento."
  },
  "Declined charge": "Cobro rechazado",
  "'%(filename)' has already been removed": "Ya se quitó “%(filename)”.",
  "Are you sure you want to remove this link? Once the link is removed, nobody else will be able to view this folder.": "¿Estás seguro de que deseas quitar este vínculo? Después de quitarlo, nadie más podrá ver esta carpeta.",
  "Find out who changed files in a shared folder": "Determinar quién cambió archivos en una carpeta compartida",
  "yearly": "anual",
  "Click here to add files, or drag them into the Dropbox folder on your Desktop.": "Haz clic aquí para agregar archivos o arrástralos a la carpeta de Dropbox de tu escritorio.",
  "There was a problem completing this request.": "Hubo un problema para completar esta solicitud.",
  "Settings changed successfully.": "La configuración se ha modificado correctamente.",
  "This folder has been moved": "Esta carpeta se movió.",
  "Photos and videos from shared folders you joined are no\n                                    longer shown.": "Ya no se muestran las fotos y los videos de las carpetas compartidas                                    a las que te uniste.",
  "Let's use shared folders to collaborate!": "Usemos carpetas compartidas para colaborar.",
  "Please confirm the topic for your question": "Confirma el tema de tu pregunta.",
  "Error updating your preference! Please try again.": "¡Error al actualizar tu preferencia! Inténtalo nuevamente.",
  "deleted image": "imagen eliminada",
  "Disable two-step verification": "Deshabilitar la verificación de dos pasos",
  "Other": "Otros",
  "Permanently delete folder?": "¿Eliminar la carpeta permanentemente?",
  "Saving...": "Guardando...",
  "Are you sure you want to make <strong>%(person_name)s</strong> an admin?": "¿Estás seguro de que deseas designar a <strong>%(person_name)s</strong> como administrador?",
  "Deleted photo.": {
    "1": "Se eliminaron las fotos.",
    "0": "Se eliminó una foto."
  },
  "%d week": {
    "1": "%d semanas",
    "0": "%d semana"
  },
  "Deselect all in %(folder)s": "Deseleccionar todos en %(folder)s",
  "Quests Complete!": "¡Tareas completadas!",
  "monthly": "mensual",
  "Copy text": "Copiar texto",
  "Jun": "Jun",
  "Jul": "Jul",
  "That photo is already in '%(collection_name)s'": {
    "1": "Esas fotos ya están en “%(collection_name)s”.",
    "0": "Esa foto ya está en “%(collection_name)s”."
  },
  "Loading photos...": "Cargando fotos...",
  "You're not allowed to nest special folders.": "No puedes anidar carpetas especiales.",
  "Change my subscription": "Cambiar mi suscripción",
  "Please enter a valid credit card number, expiration date and security code.": "Ingresa un número de tarjeta de crédito, una fecha de caducidad y un código de seguridad válidos.",
  "disk image": "imagen de disco",
  "You've added too many phone numbers. Please try again in a few minutes.": "Agregaste demasiados números de teléfono. Vuelve a intentarlo en unos minutos.",
  "Unshare": "Dejar de compartir",
  "Please enter your password": "Ingresa tu contraseña",
  "Show deleted files": "Mostrar archivos eliminados",
  "Unshare folder?": "¿Dejar de compartir la carpeta?",
  "That is not a valid phone number.": "El número telefónico no es válido.",
  "I need a copy of my invoice": "Necesito una copia de mi factura",
  "deleted document": "documento eliminado",
  "Sharing a folder": "Compartir una carpeta",
  "Please enter a valid Visa/American Express/MasterCard.": "Ingresa una tarjeta Visa, American Express o MasterCard válida.",
  "Trouble with bonus space": "Problemas con la bonificación de espacio",
  "View tweet": "Ver tweet",
  "New folder": "Nueva carpeta",
  "This folder has been renamed to '%s'.": "El nombre de esta carpeta se cambió a '%s'.",
  "Please enter a valid Visa/American Express/MasterCard, security code and postal code.": "Ingresa una tarjeta Visa, American Express o MasterCard válida, un código de seguridad válido y un código postal válido.",
  "Flash error": "Error de Flash",
  "Delete my account": "Eliminar mi cuenta",
  "Show photos with missing dates": "Mostrar fotos sin fecha",
  "New album": "Nuevo álbum",
  "Tell us what your help request is about...": "Indícanos de qué se trata tu solicitud de ayuda...",
  "%(email_or_fbname)s has been uninvited.": "Se retiró la invitación de %(email_or_fbname)s.",
  "Unshared '%(collection_name)s'": "Dejar de compartir '%(collection_name)s'",
  "You're done! It's that simple!": "¡Ya está! Es así de simple.",
  "You can't upload any files because your Dropbox is full. <a target=\"_blank\" href=\"/upgrade\">Get more space</a>": "No puedes cargar archivos porque tu Dropbox está lleno. <a target=\"_blank\" href=\"/upgrade\">Obtener más espacio</a>",
  "Size": "Tamaño",
  "%(album_name_text)s (%(album_desc)s)": "%(album_name_text)s (%(album_desc)s)",
  "All versions": "Todas las versiones",
  "How to share a folder": "Cómo compartir una carpeta",
  "Copy '%(filename)s' to my Dropbox": "Copiar '%(filename)s' a mi Dropbox",
  "Edit two-step verification": "Editar la verificación de dos pasos",
  "You": "Tú",
  "Verify email address": "Verificar dirección de correo electrónico",
  "Stolen computer": "Me robaron la computadora",
  "Out of votes": "No hay más votos",
  "Testing builds": "Compilaciones de prueba",
  "Please enter a name for this album": "Especifica un nombre para este álbum.",
  "Deleting file": {
    "1": "Eliminando archivos...",
    "0": "Eliminando archivo..."
  },
  "Remove %(app_name)s?": "¿Deseas eliminar %(app_name)s?",
  "Are you sure you want to remove this link? Once the link is removed, nobody else will be able to view this file.": "¿Estás seguro de que deseas quitar este vínculo? Después de quitarlo, nadie más podrá ver este archivo.",
  "Successfully removed Gmail contacts": "Tus contactos de Gmail se eliminaron correctamente.",
  "Restoring...": "Restaurando...",
  "Loading %(filename)s...": "Cargando %(filename)s...",
  "Hide keyboard shorcuts": "Ocultar métodos abreviados del teclado",
  "Members can no longer share this folder.": "Los miembros ya no pueden compartir esta carpeta.",
  "%d sec ago": {
    "1": "Hace %d s",
    "0": "Hace %d s"
  },
  "That item is already in '%(collection_name)s'": {
    "1": "Esos elementos ya están en “%(collection_name)s”.",
    "0": "Ese elemento ya está en “%(collection_name)s”."
  },
  "Copy": "Copiar",
  "You can't do this while uploading.": "No puedes hacer esto mientras cargas.",
  "I see 'Error 404' when I visit a link": "Cuando visito un vínculo, veo 'Error 404'",
  "My space is being counted incorrectly": "Mi espacio no se cuenta correctamente",
  "%d hour": {
    "1": "%d horas",
    "0": "%d hora"
  },
  "Transfer my upgrade to another account": "Transferir mi categoría superior a otra cuenta",
  "Enable two-step verification": "Habilitar la verificación de dos pasos",
  "In order to connect your Facebook account, Dropbox needs permission to post on your behalf.": "Para poder conectar tu cuenta de Facebook, Dropbox necesita permiso para publicar en tu nombre.",
  "Unshare this folder": "Dejar de compartir",
  "Recover a file": "Recuperar un archivo",
  "Sent to %(recipient)s and %(num_others)s others": "Se envió a %(recipient)s y %(num_others)s personas más.",
  "%(member_count)s member has two-step verification disabled": {
    "1": "%(member_count)s miembros tienen inhabilitada la verificación de dos pasos.",
    "0": "%(member_count)s miembro tiene inhabilitada la verificación de dos pasos."
  },
  "Can't share folder": "No se puede compartir la carpeta",
  "Delete %(file_count)s video": {
    "1": "Eliminar %(file_count)s videos",
    "0": "Eliminar %(file_count)s video"
  },
  "Searching...": "Buscando...",
  "Got it": "Entendido.",
  "Remove admin status": "Quitar estado de administrador",
  "Reset all passwords": "Restaurar todas las contraseñas",
  "You can't upload a file with the same name as a folder in this folder.": "No puedes cargar un archivo con el mismo nombre que una carpeta en esta carpeta.",
  "Your post must be 90 characters or less": "Tu publicación debe tener 90 caracteres o menos",
  "Sorry, it looks like the advanced uploader is incompatible with your system. Please use the <a id=\"basic_link\">basic uploader</a> to upload via the website": "Lo sentimos, parece que el cargador avanzado no es compatible con tu sistema. Usa el <a id=\"basic_link\">cargador básico</a> para cargar mediante el sitio web",
  "Folder uploads not supported. Some files will not be uploaded.": "No se admite la carga de carpetas. Algunos archivos no se cargarán.",
  "Update my credit card information": "Actualizar la información de mi tarjeta de crédito",
  "Previous versions": "Versiones anteriores",
  "We sent you another code. Keep in mind that it might take a few minutes.": "Te hemos enviado otro código. Debes tener en cuenta que esta operación podría demorar unos minutos.",
  "Link code copied to clipboard": "El código del vínculo se copió en el portapapeles.",
  "Install Dropbox": "Instalar Dropbox",
  "Shared folder options": "Opciones de carpeta compartida",
  "All files": "Todos los archivos",
  "Recover a previous version of a file": "Recuperar una versión anterior de un archivo",
  "Unsharing...": "Dejando de compartir...",
  "Sent to %(recipient_first)s and %(recipient_second)s": "Se envió a %(recipient_first)s y a %(recipient_second)s.",
  "Select this photo": "Seleccionar esta foto",
  "Add %(num_photos)s to album...": "Agregar %(num_photos)s fotos al álbum...",
  "Yesterday": "Ayer",
  "Leave shared folder": "Salir de carpeta compartida",
  "User removed.": "Se quitó el usuario.",
  "Shared folder invitations (%d)": "Invitaciones de carpetas compartidas (%d)",
  "Please enter a valid expiration date, security code and postal code.": "Ingresa una fecha de caducidad, un código de seguridad y un código postal válidos.",
  "You can see the file you just added below!": "A continuación, puedes ver el archivo que agregaste recientemente.",
  "I upgraded my Dropbox but other members are over capacity": "Actualicé mi Dropbox pero otros miembros excedieron la capacidad",
  "We cannot verify your domain ownership now, please try again later.": "En este momento no podemos verificar que seas el propietario del dominio, vuelve a intentarlo más tarde.",
  "What is %(feature_name)s?": "¿Qué es %(feature_name)s?",
  "Photo from %(date_taken)s": "Foto del %(date_taken)s",
  "Choose folder to share": "Selecciona la carpeta que deseas compartir",
  "There are multiple copies of this photo.": "Hay varias copias de esta foto.",
  "The Dropbox website can't upload more than %(max_files)s files.": "El sitio web de Dropbox no puede cargar más de %(max_files)s archivos.",
  "Photos": "Fotos",
  "Tweet about your love of Dropbox": "Envía un tuit acerca de cuánto te gusta Dropbox",
  "Weak": "Débil",
  "shortcut": "acceso directo",
  "Please enter a tweet": "Escribe un tweet.",
  "Search - Dropbox": "Buscar - Dropbox",
  "Example: ": "Ejemplo: ",
  "Creating folder...": "Creando carpeta...",
  "Added video to '%(collection_name)s'": {
    "1": "Se agregaron videos a “%(collection_name)s”.",
    "0": "Se agregó un video a “%(collection_name)s”."
  },
  "Download Dropbox": "Descargar Dropbox",
  "Report a translation problem": "Informar un problema de traducción",
  "Share %(num_videos)s videos": "Compartir %(num_videos)s videos",
  "We need your permission to import your Yahoo! Mail contacts": "Para importar tus contactos de Yahoo! Mail, necesitamos tu permiso.",
  "Copy public link": "Copiar vínculo público",
  "You removed yourself from '%(msg)s'.": "Te quitaste de '%(msg)s'.",
  "This album has been deleted!": "Se eliminó este álbum.",
  "Backup phone number removed": "Se eliminó el número de teléfono de respaldo.",
  "Change my account information": "Cambiar la información de mi cuenta",
  "Created '%(collection_name)s'": "Se ha creado'%(collection_name)s'",
  "Report untranslated text": "Informar texto sin traducir",
  "Check the Dropbox folder": "Consulta la carpeta de Dropbox",
  "Please enter a valid Visa/American Express/MasterCard and expiration date.": "Ingresa una tarjeta Visa, American Express o MasterCard válida y una fecha de caducidad válida.",
  "Restoring '%(folder_name)s'": "Restaurando “%(folder_name)s”...",
  "Still working...": "En curso...",
  "You're not allowed to put a shared folder inside a special folder.": "No puedes colocar una carpeta compartida dentro de una carpeta especial.",
  "Leave the shared folder '%(folder_name)s'": "Dejar la carpeta compartida '%(folder_name)s'",
  "Share": "Compartir",
  "%(count)s result": {
    "1": "%(count)s resultados",
    "0": "%(count)s resultado"
  },
  "Permanently delete folder": "Eliminar carpeta permanentemente",
  "We couldn't reach your phone number. Are you sure it's correct?": "No logramos comunicarnos con tu teléfono. ¿Especificaste el número correcto?",
  "How to share a link": "Cómo compartir un vínculo",
  "- %d error": {
    "1": "- %d errores",
    "0": "- %d error"
  },
  "Billed annually": "Facturación anual ",
  "Relink your computer": "Vuelve a vincular tu computadora",
  "%d month": {
    "1": "%d meses",
    "0": "%d mes"
  },
  "%(photo_video_desc)s from %(album_members)s": "%(photo_video_desc)s de %(album_members)s",
  "Delete my Dropbox account": "Eliminar mi cuenta de Dropbox",
  "1 hour ago": {
    "1": "Hace {count} horas",
    "0": "Hace {count} hora"
  },
  "Easily share with friends, family or coworkers": "Comparte fácilmente con amigos, familiares o colegas.",
  "Are you sure you want to delete '%(app_name)s'?": "¿Estás seguro de que deseas eliminar “%(app_name)s”?",
  "Add '%(filename)s' to my Dropbox": "Agregar '%(filename)s' a mi Dropbox",
  "Remove admin privileges for '%(person_name)s'": "Quitar privilegios de administrador a “%(person_name)s”",
  "A good password is easy to remember but hard for a stranger to guess. Uncommon words work well, but only if you use several. Also helpful: non-standard uPPercasing, creative spelllling, personal neologisms, and non-obvious numbers and symbols (using $ for s or 0 for o is too obvious!)": "Las buenas contraseñas son fáciles de recordar para ti y difíciles de adivinar para los extraños. Las palabras difíciles funcionan bien, pero solo si usas varias. Otras cosas útiles: mAyúSCulas no estándar, ortografía creativa, neologismos personales, y números y símbolos que no sean obvios (¡usar $ en lugar de s o 0 en lugar de o es muy obvio!)",
  "Prevent unauthorized access to my Dropbox account": "Prevenir el acceso no autorizado a mi cuenta de Dropbox",
  "Please enter a valid Visa/American Express/MasterCard and postal code.": "Ingresa una tarjeta Visa, American Express o MasterCard válida y un código postal válido.",
  "Message shared!": "Se compartió correctamente el mensaje.",
  "Email": "Correo electrónico",
  "Rejoin the shared folder '%(folder_name)s'?": "¿Deseas volver a unirte a la carpeta compartida '%(folder_name)s'?",
  "No results": "No hay resultados",
  "Share link to photo": "Compartir vínculo a foto",
  "You're not allowed to move shared folders to your Public folder.": "No puedes mover carpetas compartidas a tu carpeta Pública.",
  "Tutorial: Sharing a folder": "Tutorial: compartir una carpeta",
  "Please enter a valid Visa/American Express/MasterCard, expiration date and security code.": "Ingresa una tarjeta Visa, American Express o MasterCard válida, una fecha de caducidad válida y un código de seguridad válido.",
  "Update billing information": "Actualizar la información de facturación",
  "How voting works": "Cómo funcionan las votaciones",
  "Share %(num_files)s items": "Compartir %(num_files)s elementos",
  "Facebook": "Facebook",
  "Un-select photo": "Deshacer selección de foto",
  "My links are banned": "Mis vínculos están prohibidos",
  "Added item to '%(collection_name)s'": {
    "1": "Se agregaron elementos a la colección “%(collection_name)s”.",
    "0": "Se agregó un elemento a la colección “%(collection_name)s”."
  },
  "Uploaded %(num_files)d files": "Se cargaron %(num_files)d archivos.",
  "You're already connected to %(service_name)s": "Ya estás conectado a %(service_name)s.",
  "Bug report": "Informe de errores",
  "Copy file to...": "Copiar archivo en...",
  "Please enter a valid credit card number and expiration date.": "Ingresa un número de tarjeta de crédito y una fecha de caducidad válidos.",
  "The link to %(album_name)s was copied to your clipboard": "El vínculo a %(album_name)s se copió a tu portapapeles.",
  "Please enter a valid credit card number, expiration date and postal code.": "Ingresa un número de tarjeta de crédito, una fecha de caducidad y un código postal válidos.",
  "Subscribe to this RSS feed": "Suscríbete a esta fuente RSS",
  "Files aren't showing up": "Los archivos no aparecen",
  "Please enter a valid security code and postal code.": "Ingresa un código de seguridad y un código postal válidos.",
  "Permanently deleted %d item": {
    "1": "Se eliminaron permanentemente %d elementos.",
    "0": "Se eliminó permanentemente %d elemento."
  },
  "Stable builds": "Compilaciones estables",
  "Edit backup phone number": "Editar número de teléfono de respaldo",
  "August": "Agosto",
  "Two-step verification updated": "Se actualizó la verificación de dos pasos.",
  "File too large": "El archivo es demasiado grande",
  "Your post must be 140 characters or less": "Tu publicación debe tener 140 caracteres o menos",
  "Select video": "Seleccionar video",
  "Invite more people": "Invitar más gente",
  "December": "Diciembre",
  "The folder '%s' has been renamed. <a href=\"/home%s\">View</a>": "Se modificó el nombre de la carpeta “%s”. <a href=\"/home%s\">Ver</a>",
  "Selecting photos...": "Seleccionando fotos...",
  "This album is empty. Add some photos before you share it!": "Este álbum está vacío. Agrega algunas fotos antes de compartirlo.",
  "Canceled": "Cancelado",
  "Share %(file_count)s photo": {
    "1": "Compartir %(file_count)s fotos",
    "0": "Compartir %(file_count)s foto"
  },
  "Invite sent.": "Invitación enviada.",
  "Please enter your name": "Ingresa tu nombre",
  "No available actions": "No hay acciones disponibles",
  "More options...": "Más opciones...",
  "app folder": "carpeta de aplicación",
  "Share a folder": "Compartir una carpeta",
  "Feb": "Feb",
  "Billing": "Facturación",
  "Report account issue": "Informar sobre un problema con una cuenta",
  "Report other translation problem": "Informar otro problema de traducción",
  "Recover a folder": "Recuperar una carpeta",
  "Basic search": "Búsqueda básica",
  "Resend invite to '%(email_address)s'": "Volver a enviar invitación a '%(email_address)s'",
  "Delete album": "Eliminar álbum",
  "Just shared some files using @Dropbox": "Compartí unos archivos utilizando @Dropbox",
  "Show %(category_name)s": "Mostrar %(category_name)s",
  "Un-select video": "Deshacer selección de video",
  "Share on Twitter": "Compartir en Twitter",
  "Invalid code.": "El código no es válido.",
  "Just shared an album using @Dropbox": "Álbum recientemente compartido a través de @Dropbox.",
  "View all albums": "Ver todos los álbumes",
  "Rename selected files": "Cambiar nombre de los archivos seleccionados",
  "Then click the link icon to share. Try it!": "Luego, para compartir, haz clic en el icono del vínculo. Inténtalo!",
  "Message successfully sent.": "El mensaje se envió correctamente.",
  "Successfully <a id='twitter-post-link'>posted</a> to Twitter.": "Se <a id='twitter-post-link'>publicó</a> en Twitter correctamente.",
  "Please choose at least one contact.": "Debes seleccionar al menos un contacto.",
  "Two-step verification is already enabled. Did you maybe enable it in another window?": "La verificación de dos pasos ya está habilitada. ¿Quizás la habilitaste en otra ventana?",
  "Great!": "¡Excelente!",
  "Sharing a link": "Compartir un vínculo",
  "Show photos with multiple copies": "Mostrar fotos con varias copias",
  "Select the folder to share": "Selecciona la carpeta que deseas compartir.",
  "November": "Noviembre",
  "%(cur_file_num)s of %(num_total_files)s": "%(cur_file_num)s de %(num_total_files)s",
  "More actions": "Más acciones",
  "Would you like to delete them all?": "¿Deseas eliminar todo?",
  "I'm out of space": "Se me terminó el espacio",
  "Unfortunately, your carrier is not supported at this time.": "Lamentablemente, no es posible utilizar tu prestador de servicios.",
  "Invalid security code": "El código de seguridad no es válido",
  "January": "Enero",
  "Reset password for '%(user_name)s'": "Restablecer contraseña para '%(user_name)s'",
  "Delete all copies of this video?": "¿Deseas eliminar todas las copias de este video?",
  "Restore app folder": "Restaurar carpeta de aplicación",
  "link": "vínculo",
  "Ownership changed successfully.": "El propietario se modificó correctamente.",
  "Add a backup phone number": "Agregar un número de teléfono de respaldo",
  "ALBUMS": "ÁLBUMES",
  "Dec": "Dic",
  "Undo recent move/copy/rename/delete": "Deshacer acción reciente de mover/copiar/cambiar el nombre/borrar",
  "Unshare?": "¿Deseas dejar de compartir?",
  "Share video": "Compartir video",
  "I don't have an account": "No tengo una cuenta.",
  "Removing...": "Quitando...",
  "I can't see the latest versions of my files": "No puedo ver las últimas versiones de mis archivos",
  "Pay with credit card": "Pagar con tarjeta de crédito",
  "Sample email": "Correo electrónico de muestra",
  "Thanks for your feedback!": "¡Gracias por tus comentarios!",
  "View recovery code": "Ver código de recuperación",
  "Yesterday %(time)s": "Ayer %(time)s",
  "Move file to...": "Mover archivo a...",
  "Which folder would you like to view?": "¿Qué carpeta deseas ver?",
  "Please enter the security code": "Introduce el código de seguridad",
  "Choose an album": "Elije un álbum",
  "%d hour ago": {
    "1": "Hace %d horas",
    "0": "Hace %d hora"
  },
  "Following Dropbox on Twitter...": "Siguiendo a Dropbox en Twitter...",
  "Recover a shared folder": "Recuperar una carpeta compartida",
  "Share 1 photo": "Compartir 1 foto",
  "Permanently remove": "Quitar permanentemente",
  "Once you sign in to Dropbox, the photos and videos in this album will be instantly copied to your Dropbox and downloaded to all the computers linked to your account.": "Una vez que inicies sesión en Dropbox, las fotos y los videos de este álbum se copiarán inmediatamente a tu Dropbox y se descargarán en todas las computadoras vinculadas a tu cuenta.",
  "We've successfully updated your team's billing information.": "Actualizamos correctamente la información de facturación de tu equipo.",
  "We couldn't send this album. Please try again.": "No se pudo enviar este álbum. Vuelve a intentarlo.",
  "deleted folder": "carpeta eliminada",
  "Panda working on her desktop computer": "Panda que trabaja en su computadora de escritorio.",
  "Shared %(album_name)s with %(first_name_of_recipient)s and %(first_name_of_second_recipient)s": "Se compartió el álbum %(album_name)s con %(first_name_of_recipient)s y %(first_name_of_second_recipient)s.",
  "File recovery": "Recuperación de archivos",
  "October": "Octubre",
  "file": "archivo",
  "Adding to album...": "Agregando a álbum...",
  "I didn't know my subscription automatically renewed": "No sabía que mi suscripción se renovaba automáticamente",
  "Unable to load photos": "No se pueden cargar fotos",
  "That video is already in '%(collection_name)s'": {
    "1": "Esos videos ya están en “%(collection_name)s”.",
    "0": "Ese video ya está en “%(collection_name)s”."
  },
  "Mar": "Mar",
  "Report other problem": "Informar otro problema",
  "May": "Mayo",
  "Link to %(album_name)s": "Vínculo a %(album_name)s",
  "I no longer need my Dropbox Pro account": "Ya no necesito mi cuenta de Dropbox Pro",
  "Creating album...": "Creando álbum...",
  "I receive some other error": "Recibo otro error",
  "Dropbox for %(device)s": "Dropbox para %(device)s",
  "Moved %(count)d item to '<a id=\"reload-link\">%(location)s</a>'.": {
    "1": "Se movieron %(count)d artículos a<a id=\"reload-link\">“%(location)s”.</a>",
    "0": "Se movió %(count)d artículo a “<a id=\"reload-link\">%(location)s</a>”."
  },
  "Mac": "Mac",
  "Disable": "Deshabilitar",
  "Please enter a search": "Escribe una búsqueda.",
  "Unshare '%(folder_name)s'": "Dejar de compartir '%(folder_name)s'",
  "TB": "TB",
  "Disconnecting your account from Facebook...": "Desvinculando tu cuenta de Facebook...",
  "Waiting for you to add a file": "Esperando que agregues un archivo",
  "Undo complete.": "Deshacer completo.",
  "February": "Febrero",
  "Posted your tweet": "Tu tweet se publicó.",
  "Windows": "Windows",
  "Unable to upload %(filename)s": "No se pudo cargar %(filename)s",
  "AM": "a. m.",
  "Remove": "Quitar",
  "March": "Marzo",
  "April": "Abril",
  "Didn't receive bonus space for Samsung phone": "No recibí la bonificación de espacio por el teléfono Samsung.",
  "Two-step verification is not enabled": "La verificación de dos pasos no está habilitada.",
  "Sorry! This file name is not allowed.": "Lamentablemente, este nombre de archivo no está permitido.",
  "Move %(item_count)s item to...": {
    "1": "Mover %(item_count)s elementos a...",
    "0": "Mover %(item_count)s elemento a..."
  },
  "Create new album": "Crear nuevo álbum",
  "Shared folder options for '%(file_name)s'": "Opciones de carpeta compartida para '%(file_name)s'",
  "Please enable browser-cookies to use the Dropbox website.": "Para usar el sitio web de Dropbox, habilita las cookies del explorador.",
  "Share folder": "Compartir carpeta",
  "Make admin": "Hacer administrador",
  "Uploaded %(num_completed)d of %(num_files)d files": "Se cargaron %(num_completed)d archivos de %(num_files)d",
  "Restore app folder '%(filename)s'": "Restaurar la carpeta de aplicación '%(filename)s'",
  "Confirm disable": "Confirmar deshabilitación",
  "Too many invalid codes. Try again in a few minutes.": "Demasiados códigos no válidos. Vuelve a intentarlo en unos minutos."
};
